INSERT INTO tb_pacientes (email, senha, nome_completo, cpf, data_nascimento, telefone,
                          logradouro, numero, bairro, cidade, estado, cep, ativo)
VALUES ('paciente@email.com',
        '$2a$12$EpAmOaWrO4q1j/tyDqF3Ve8S8RLT48tI97papdnTbTfQ8K4e.sgzu',
        'Paciente Teste',
        '11111111001',
        '1990-01-01',
        '(11) 99999-9999',
        'Rua Exemplo',
        '123',
        'Centro',
        'São Paulo',
        'SP',
        '01000000',
        true);

-- Inserir funcionários seed diretamente
INSERT INTO tb_funcionarios (email, senha, tipo, nome_completo, cpf, crm, coren,
                             especialidade_nome, especialidade_codigo, ativo, data_cadastro)
VALUES ('admin@email.com',
        '$2a$12$EpAmOaWrO4q1j/tyDqF3Ve8S8RLT48tI97papdnTbTfQ8K4e.sgzu',
        'ADMIN',
        'Administrador Sistema',
        '22222222001',
        NULL,
        NULL,
        NULL,
        NULL,
        true,
        CURRENT_TIMESTAMP),
       ('medico@email.com',
        '$2a$12$EpAmOaWrO4q1j/tyDqF3Ve8S8RLT48tI97papdnTbTfQ8K4e.sgzu',
        'MEDICO',
        'Dr. Médico',
        '33333333002',
        'CRM000002-SP',
        NULL,
        'CLINICA GERAL',
        'CG001',
        true,
        CURRENT_TIMESTAMP),
       ('enfermeiro@email.com',
        '$2a$12$EpAmOaWrO4q1j/tyDqF3Ve8S8RLT48tI97papdnTbTfQ8K4e.sgzu',
        'ENFERMEIRO',
        'Enfermeiro(a)',
        '44444444003',
        NULL,
        'COREN000003-SP',
        NULL,
        NULL,
        true,
        CURRENT_TIMESTAMP);