eureka.client.serviceUrl.defaultZone=http://server:8761/eureka

spring.datasource.url=jdbc:postgresql://postgres:5432/db_atendimento
spring.datasource.username=admin
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.rabbitmq.host=rabbitmq

eureka.instance.hostname=atendimento
services.agendamento.url=http://agendamento:8080
services.autenticacao.url=http://autenticacao:8080

service.id=atendimento-service
service.secret=${ATENDIMENTO_SECRET}
